---
title: "Lesson 6: Geographic Segmentation with Spatially Constrained Cluster Analysis"
date: "July 21, 2024"
date-modified: "last-modified"
output:
  html:
    toc: true
    toc_depth: 3
execute: 
  freeze: true
---

## Overview

## Content

- Basic concepts of geographic segmentation
- Conventional cluster analysis techniques
- Approaches for clustering geographically referenced data
  - Hierarchical clustering with spatial constraints
  - Minimum spanning trees
  - ClustGeo method

## Lesson slides

- [Lesson 6: Geographic Segmentation with Spatially Constrained Cluster Analysis](..\lesson\Lesson06\Lesson06.html) slides.

## Hands-on Exercise

- [12 Geographical Segmentation with Spatially Constrained Clustering Techniques](https://r4gdsa.netlify.app/chap12.html)

### Self-reading Before Meet-up

To read before class:

- Assuncao, R. M., Neves, M.C., Camara, G. and Costa Freitas, C.D. 2006. "Efficient Regionalization Techniques for Socio-Economic Geographical Units Using Minimum Spanning Trees". *International Journal of Geographical Information Science* 20: 797-811. (Available in SMU digital library)

- Chavent, M., Kuentz-Simonet, V., Labenne,A. and Saracco, J. 2018. "ClustGeo: an R package for hierarchical clustering with spatial constraints" *Computational Statistics*, 33: 1799-1822. (Available in SMU digital library)

### References

- Rovan, J. and Sambt, J. (2003) ["Socio-economic Differences Among Slovenian Municipalities: A Cluster Analysis Approach"](http://mrvar.fdv.uni-lj.si/pub/mz/mz19/rovan.pdf), *Developments in Applied Statistics*, pp. 265-278.\
- Demeter, T. and Bratucu, G. (2013) ["Statistical Analysis Of The EU Countries from A Touristic Point of View"](https://webbut.unitbv.ro/index.php/Series_V/article/view/5438), *Bulletin of the Transilvania University of Braşov*, 6(55): 121-130.
- Brown, N.S. & Watson, P. (2012) ["What can a comprehensive plan really tell us about a region?: A cluster analysis of county comprehensive plans in Idaho"](https://ageconsearch.umn.edu/record/176591/files/WEFFall2012v11n2_Brown.pdf), Western Economics Forum. Pp.22-37.
- Jaya, I.G.M., Ruchjana, B.N., Andriyana, Y. & Agata, R (2019) ["Clustering with spatial constraints: The case of diarrhea in Bandung city, Indonesia"](https://iopscience.iop.org/article/10.1088/1742-6596/1397/1/012068)
- de Souza, D. C. & Taconeli, C. A. (2022) "Spatial and non-spatial clustering algorithm in the analysis of Brazilian educational data", *Communications in Statistics: Case Studies, Data Analysis, and Applications*. Vol. 8, No. 4, 588-606. (Available in SMU digital library)

### All About R

- [Hierarchical Cluster Analysis](http://uc-r.github.io/hc_clustering).
- [skater](https://www.rdocumentation.org/packages/spdep/versions/0.8-1/topics/skater): A function from spdep package that implements a SKATER procedure for spatial clustering analysis.
- [ClustGeo: Hierarchical Clustering with Spatial Constraints](https://cran.r-project.org/web/packages/ClustGeo/index.html)
  - [Introduction to Clustgeo](https://cran.r-project.org/web/packages/ClustGeo/vignettes/intro_ClustGeo.html)